<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-07C5PU1R" failures="2" tests="6" name="Test" time="48.984" errors="0" timestamp="2025-05-31T09:55:45 IST">
  <testcase classname="testCases.AccountRegistrationTest" name="verify_Account_Registration" time="1.83">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.AccountRegistrationTest.verify_Account_Registration(AccountRegistrationTest.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verify_Account_Registration -->
  <testcase classname="testCases.LoginTest" name="TC002_verifyLoginFunctionality" time="2.69"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_LoginDDT" time="1.698"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_LoginDDT" time="10.785"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_LoginDDT" time="10.75"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_LoginDDT" time="10.785">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginDDT.verify_LoginDDT(TC003_LoginDDT.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verify_LoginDDT -->
</testsuite> <!-- Test -->
